[package]
name = "battleships"
version = "0.1.0"
edition = "2021"

[dependencies]
iced = { version = "0.13.1", features = ["image"] }
rand = "0.8.5"
serde = { version = "1.0.217", features = ["derive"] }
toml = "0.8.19"
